### ISSUE TITLE
Error when run simulator with specific port

### ISSUE THREAD

**Issue by lylyjy** [rohjunha/multiple-topologies-prediction#1]
Is ${ROOT} the name of this project?
Where is  ./CarlaUE4.sh?
Thanks.

**Comment by rohjunha** [comment]
Hi @lylyjy,

No, `${ROOT}` is the directory you extracted the code.
For instance, if you clone this project on `$HOME/projects/multiple-topologies-prediction`, this will be `${ROOT}`.

I think you need to follow the installation steps listed here: https://github.com/rohjunha/multiple-topologies-prediction#install-guide.
It first installs conda, sets up the environment, installs some required packages through pip, downloads CARLA binary, and pre-trained models.
Then you can find `CarlaUE4.sh` from the directory in which CARLA is installed, `${ROOT}/.carla`.
Hope you make the code work.
